import type { Pokemon, Rarity } from '../types/pokemon'

export const POKEMON_DATA: Pokemon[] = [
  // Common Pokemon
  {
    id: 1,
    name: 'Bulbasaur',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
    baseStats: { hp: 45, attack: 49, defense: 49, speed: 45 },
    rarity: 'common',
    evolvesTo: 2,
    evolutionLevel: 16,
  },
  {
    id: 2,
    name: 'Ivysaur',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
    baseStats: { hp: 60, attack: 62, defense: 63, speed: 60 },
    rarity: 'uncommon',
    evolvesTo: 3,
    evolutionLevel: 32,
  },
  {
    id: 3,
    name: 'Venusaur',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
    baseStats: { hp: 80, attack: 82, defense: 83, speed: 80 },
    rarity: 'epic',
  },
  {
    id: 4,
    name: 'Charmander',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    baseStats: { hp: 39, attack: 52, defense: 43, speed: 65 },
    rarity: 'common',
    evolvesTo: 5,
    evolutionLevel: 16,
  },
  {
    id: 5,
    name: 'Charmeleon',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
    baseStats: { hp: 58, attack: 64, defense: 58, speed: 80 },
    rarity: 'uncommon',
    evolvesTo: 6,
    evolutionLevel: 36,
  },
  {
    id: 6,
    name: 'Charizard',
    types: ['Fire', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
    baseStats: { hp: 78, attack: 84, defense: 78, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 7,
    name: 'Squirtle',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    baseStats: { hp: 44, attack: 48, defense: 65, speed: 43 },
    rarity: 'common',
    evolvesTo: 8,
    evolutionLevel: 16,
  },
  {
    id: 8,
    name: 'Wartortle',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
    baseStats: { hp: 59, attack: 63, defense: 80, speed: 58 },
    rarity: 'uncommon',
    evolvesTo: 9,
    evolutionLevel: 36,
  },
  {
    id: 9,
    name: 'Blastoise',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
    baseStats: { hp: 79, attack: 83, defense: 100, speed: 78 },
    rarity: 'legendary',
  },
  {
    id: 10,
    name: 'Caterpie',
    types: ['Bug'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
    baseStats: { hp: 45, attack: 30, defense: 35, speed: 45 },
    rarity: 'common',
    evolvesTo: 11,
    evolutionLevel: 7,
  },
  {
    id: 11,
    name: 'Metapod',
    types: ['Bug'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
    baseStats: { hp: 50, attack: 20, defense: 55, speed: 30 },
    rarity: 'common',
    evolvesTo: 12,
    evolutionLevel: 10,
  },
  {
    id: 12,
    name: 'Butterfree',
    types: ['Bug', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
    baseStats: { hp: 60, attack: 45, defense: 50, speed: 70 },
    rarity: 'uncommon',
  },
  {
    id: 13,
    name: 'Weedle',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
    baseStats: { hp: 40, attack: 35, defense: 30, speed: 50 },
    rarity: 'common',
    evolvesTo: 14,
    evolutionLevel: 7,
  },
  {
    id: 14,
    name: 'Kakuna',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
    baseStats: { hp: 45, attack: 25, defense: 50, speed: 35 },
    rarity: 'common',
    evolvesTo: 15,
    evolutionLevel: 10,
  },
  {
    id: 15,
    name: 'Beedrill',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
    baseStats: { hp: 65, attack: 90, defense: 40, speed: 75 },
    rarity: 'uncommon',
  },
  {
    id: 16,
    name: 'Pidgey',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
    baseStats: { hp: 40, attack: 45, defense: 40, speed: 56 },
    rarity: 'common',
    evolvesTo: 17,
    evolutionLevel: 18,
  },
  {
    id: 17,
    name: 'Pidgeotto',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
    baseStats: { hp: 63, attack: 60, defense: 55, speed: 71 },
    rarity: 'uncommon',
    evolvesTo: 18,
    evolutionLevel: 36,
  },
  {
    id: 18,
    name: 'Pidgeot',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
    baseStats: { hp: 83, attack: 80, defense: 75, speed: 101 },
    rarity: 'rare',
  },
  {
    id: 19,
    name: 'Rattata',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
    baseStats: { hp: 30, attack: 56, defense: 35, speed: 72 },
    rarity: 'common',
    evolvesTo: 20,
    evolutionLevel: 20,
  },
  {
    id: 20,
    name: 'Raticate',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
    baseStats: { hp: 55, attack: 81, defense: 60, speed: 97 },
    rarity: 'uncommon',
  },
  {
    id: 25,
    name: 'Pikachu',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    baseStats: { hp: 35, attack: 55, defense: 40, speed: 90 },
    rarity: 'uncommon',
    evolvesTo: 26,
    evolutionLevel: 25,
  },
  {
    id: 26,
    name: 'Raichu',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',
    baseStats: { hp: 60, attack: 90, defense: 55, speed: 110 },
    rarity: 'rare',
  },
  // Uncommon Pokemon
  {
    id: 35,
    name: 'Clefairy',
    types: ['Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
    baseStats: { hp: 70, attack: 45, defense: 48, speed: 35 },
    rarity: 'uncommon',
    evolvesTo: 36,
    evolutionLevel: 25,
  },
  {
    id: 36,
    name: 'Clefable',
    types: ['Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',
    baseStats: { hp: 95, attack: 70, defense: 73, speed: 60 },
    rarity: 'rare',
  },
  {
    id: 37,
    name: 'Vulpix',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
    baseStats: { hp: 38, attack: 41, defense: 40, speed: 65 },
    rarity: 'uncommon',
    evolvesTo: 38,
    evolutionLevel: 25,
  },
  {
    id: 38,
    name: 'Ninetales',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',
    baseStats: { hp: 73, attack: 76, defense: 75, speed: 100 },
    rarity: 'rare',
  },
  {
    id: 39,
    name: 'Jigglypuff',
    types: ['Normal', 'Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
    baseStats: { hp: 115, attack: 45, defense: 20, speed: 20 },
    rarity: 'uncommon',
    evolvesTo: 40,
    evolutionLevel: 25,
  },
  {
    id: 40,
    name: 'Wigglytuff',
    types: ['Normal', 'Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',
    baseStats: { hp: 140, attack: 70, defense: 45, speed: 45 },
    rarity: 'rare',
  },
  {
    id: 41,
    name: 'Zubat',
    types: ['Poison', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 55 },
    rarity: 'uncommon',
    evolvesTo: 42,
    evolutionLevel: 22,
  },
  {
    id: 42,
    name: 'Golbat',
    types: ['Poison', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',
    baseStats: { hp: 75, attack: 80, defense: 70, speed: 90 },
    rarity: 'rare',
  },
  {
    id: 43,
    name: 'Oddish',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
    baseStats: { hp: 45, attack: 50, defense: 55, speed: 30 },
    rarity: 'uncommon',
    evolvesTo: 44,
    evolutionLevel: 21,
  },
  {
    id: 44,
    name: 'Gloom',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',
    baseStats: { hp: 60, attack: 65, defense: 70, speed: 40 },
    rarity: 'uncommon',
    evolvesTo: 45,
    evolutionLevel: 30,
  },
  {
    id: 45,
    name: 'Vileplume',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',
    baseStats: { hp: 75, attack: 80, defense: 85, speed: 50 },
    rarity: 'rare',
  },
  {
    id: 50,
    name: 'Diglett',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',
    baseStats: { hp: 10, attack: 55, defense: 25, speed: 95 },
    rarity: 'uncommon',
    evolvesTo: 51,
    evolutionLevel: 26,
  },
  {
    id: 51,
    name: 'Dugtrio',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png',
    baseStats: { hp: 35, attack: 80, defense: 50, speed: 120 },
    rarity: 'rare',
  },
  {
    id: 52,
    name: 'Meowth',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 90 },
    rarity: 'uncommon',
    evolvesTo: 53,
    evolutionLevel: 28,
  },
  {
    id: 53,
    name: 'Persian',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png',
    baseStats: { hp: 65, attack: 70, defense: 60, speed: 115 },
    rarity: 'rare',
  },
  {
    id: 54,
    name: 'Psyduck',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
    baseStats: { hp: 50, attack: 52, defense: 48, speed: 55 },
    rarity: 'uncommon',
    evolvesTo: 55,
    evolutionLevel: 33,
  },
  {
    id: 55,
    name: 'Golduck',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png',
    baseStats: { hp: 80, attack: 82, defense: 78, speed: 80 },
    rarity: 'rare',
  },
  // Rare Pokemon
  {
    id: 58,
    name: 'Growlithe',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
    baseStats: { hp: 55, attack: 70, defense: 45, speed: 60 },
    rarity: 'rare',
    evolvesTo: 59,
    evolutionLevel: 25,
  },
  {
    id: 59,
    name: 'Arcanine',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png',
    baseStats: { hp: 90, attack: 110, defense: 80, speed: 95 },
    rarity: 'legendary',
  },
  {
    id: 60,
    name: 'Poliwag',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
    baseStats: { hp: 40, attack: 50, defense: 40, speed: 90 },
    rarity: 'rare',
    evolvesTo: 61,
    evolutionLevel: 25,
  },
  {
    id: 61,
    name: 'Poliwhirl',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png',
    baseStats: { hp: 65, attack: 65, defense: 65, speed: 90 },
    rarity: 'rare',
    evolvesTo: 62,
    evolutionLevel: 35,
  },
  {
    id: 62,
    name: 'Poliwrath',
    types: ['Water', 'Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png',
    baseStats: { hp: 90, attack: 95, defense: 95, speed: 70 },
    rarity: 'legendary',
  },
  {
    id: 63,
    name: 'Abra',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
    baseStats: { hp: 25, attack: 20, defense: 15, speed: 90 },
    rarity: 'rare',
    evolvesTo: 64,
    evolutionLevel: 16,
  },
  {
    id: 64,
    name: 'Kadabra',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png',
    baseStats: { hp: 40, attack: 35, defense: 30, speed: 105 },
    rarity: 'rare',
    evolvesTo: 65,
    evolutionLevel: 30,
  },
  {
    id: 65,
    name: 'Alakazam',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png',
    baseStats: { hp: 55, attack: 50, defense: 45, speed: 120 },
    rarity: 'legendary',
  },
  {
    id: 66,
    name: 'Machop',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
    baseStats: { hp: 70, attack: 80, defense: 50, speed: 35 },
    rarity: 'rare',
    evolvesTo: 67,
    evolutionLevel: 28,
  },
  {
    id: 67,
    name: 'Machoke',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png',
    baseStats: { hp: 80, attack: 100, defense: 70, speed: 45 },
    rarity: 'rare',
    evolvesTo: 68,
    evolutionLevel: 40,
  },
  {
    id: 68,
    name: 'Machamp',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png',
    baseStats: { hp: 90, attack: 130, defense: 80, speed: 55 },
    rarity: 'legendary',
  },
  {
    id: 69,
    name: 'Bellsprout',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
    baseStats: { hp: 50, attack: 75, defense: 35, speed: 40 },
    rarity: 'rare',
    evolvesTo: 70,
    evolutionLevel: 21,
  },
  {
    id: 70,
    name: 'Weepinbell',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png',
    baseStats: { hp: 65, attack: 90, defense: 50, speed: 55 },
    rarity: 'rare',
    evolvesTo: 71,
    evolutionLevel: 30,
  },
  {
    id: 71,
    name: 'Victreebel',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png',
    baseStats: { hp: 80, attack: 105, defense: 65, speed: 70 },
    rarity: 'legendary',
  },
  {
    id: 72,
    name: 'Tentacool',
    types: ['Water', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
    baseStats: { hp: 40, attack: 40, defense: 35, speed: 70 },
    rarity: 'rare',
    evolvesTo: 73,
    evolutionLevel: 30,
  },
  {
    id: 73,
    name: 'Tentacruel',
    types: ['Water', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png',
    baseStats: { hp: 80, attack: 70, defense: 65, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 74,
    name: 'Geodude',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
    baseStats: { hp: 40, attack: 80, defense: 100, speed: 20 },
    rarity: 'rare',
    evolvesTo: 75,
    evolutionLevel: 25,
  },
  {
    id: 75,
    name: 'Graveler',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png',
    baseStats: { hp: 55, attack: 95, defense: 115, speed: 35 },
    rarity: 'rare',
    evolvesTo: 76,
    evolutionLevel: 40,
  },
  {
    id: 76,
    name: 'Golem',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png',
    baseStats: { hp: 80, attack: 120, defense: 130, speed: 45 },
    rarity: 'legendary',
  },
  {
    id: 77,
    name: 'Ponyta',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
    baseStats: { hp: 50, attack: 85, defense: 55, speed: 90 },
    rarity: 'rare',
    evolvesTo: 78,
    evolutionLevel: 40,
  },
  {
    id: 78,
    name: 'Rapidash',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png',
    baseStats: { hp: 65, attack: 100, defense: 70, speed: 105 },
    rarity: 'legendary',
  },
  {
    id: 79,
    name: 'Slowpoke',
    types: ['Water', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
    baseStats: { hp: 90, attack: 65, defense: 65, speed: 15 },
    rarity: 'rare',
    evolvesTo: 80,
    evolutionLevel: 37,
  },
  {
    id: 80,
    name: 'Slowbro',
    types: ['Water', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png',
    baseStats: { hp: 95, attack: 75, defense: 110, speed: 30 },
    rarity: 'legendary',
  },
  {
    id: 81,
    name: 'Magnemite',
    types: ['Electric', 'Steel'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
    baseStats: { hp: 25, attack: 35, defense: 70, speed: 45 },
    rarity: 'rare',
    evolvesTo: 82,
    evolutionLevel: 30,
  },
  {
    id: 82,
    name: 'Magneton',
    types: ['Electric', 'Steel'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
    baseStats: { hp: 50, attack: 60, defense: 95, speed: 70 },
    rarity: 'legendary',
  },
  // Epic Pokemon
  {
    id: 83,
    name: 'Farfetchd',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
    baseStats: { hp: 52, attack: 90, defense: 55, speed: 60 },
    rarity: 'epic',
  },
  {
    id: 86,
    name: 'Seel',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
    baseStats: { hp: 65, attack: 45, defense: 55, speed: 45 },
    rarity: 'epic',
  },
  {
    id: 88,
    name: 'Grimer',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
    baseStats: { hp: 80, attack: 80, defense: 50, speed: 25 },
    rarity: 'epic',
  },
  {
    id: 90,
    name: 'Shellder',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
    baseStats: { hp: 30, attack: 65, defense: 100, speed: 40 },
    rarity: 'epic',
  },
  {
    id: 92,
    name: 'Gastly',
    types: ['Ghost', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
    baseStats: { hp: 30, attack: 35, defense: 30, speed: 80 },
    rarity: 'epic',
  },
  {
    id: 95,
    name: 'Onix',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
    baseStats: { hp: 35, attack: 45, defense: 160, speed: 70 },
    rarity: 'epic',
  },
  {
    id: 96,
    name: 'Drowzee',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
    baseStats: { hp: 60, attack: 48, defense: 45, speed: 42 },
    rarity: 'epic',
  },
  {
    id: 98,
    name: 'Krabby',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
    baseStats: { hp: 30, attack: 105, defense: 90, speed: 50 },
    rarity: 'epic',
  },
  {
    id: 100,
    name: 'Voltorb',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
    baseStats: { hp: 40, attack: 30, defense: 50, speed: 100 },
    rarity: 'epic',
  },
  {
    id: 104,
    name: 'Cubone',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png',
    baseStats: { hp: 50, attack: 50, defense: 95, speed: 35 },
    rarity: 'epic',
    evolvesTo: 105,
    evolutionLevel: 28,
  },
  {
    id: 105,
    name: 'Marowak',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png',
    baseStats: { hp: 60, attack: 80, defense: 110, speed: 45 },
    rarity: 'legendary',
  },
  // Legendary Pokemon
  {
    id: 123,
    name: 'Scyther',
    types: ['Bug', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
    baseStats: { hp: 70, attack: 110, defense: 80, speed: 105 },
    rarity: 'legendary',
  },
  {
    id: 124,
    name: 'Jynx',
    types: ['Ice', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
    baseStats: { hp: 65, attack: 50, defense: 35, speed: 95 },
    rarity: 'legendary',
  },
  {
    id: 126,
    name: 'Magmar',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
    baseStats: { hp: 65, attack: 95, defense: 57, speed: 93 },
    rarity: 'legendary',
  },
  {
    id: 129,
    name: 'Magikarp',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
    baseStats: { hp: 20, attack: 10, defense: 55, speed: 80 },
    rarity: 'common',
    evolvesTo: 130,
    evolutionLevel: 20,
  },
  {
    id: 130,
    name: 'Gyarados',
    types: ['Water', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png',
    baseStats: { hp: 95, attack: 125, defense: 79, speed: 81 },
    rarity: 'legendary',
  },
  {
    id: 131,
    name: 'Lapras',
    types: ['Water', 'Ice'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png',
    baseStats: { hp: 130, attack: 85, defense: 80, speed: 60 },
    rarity: 'legendary',
  },
  {
    id: 133,
    name: 'Eevee',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    baseStats: { hp: 55, attack: 55, defense: 50, speed: 55 },
    rarity: 'rare',
    evolvesTo: 135,
    evolutionLevel: 20,
  },
  {
    id: 135,
    name: 'Jolteon',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
    baseStats: { hp: 65, attack: 65, defense: 60, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 137,
    name: 'Vaporeon',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png',
    baseStats: { hp: 130, attack: 65, defense: 60, speed: 65 },
    rarity: 'legendary',
  },
  {
    id: 143,
    name: 'Snorlax',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
    baseStats: { hp: 160, attack: 110, defense: 65, speed: 30 },
    rarity: 'legendary',
  },
  {
    id: 144,
    name: 'Articuno',
    types: ['Ice', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png',
    baseStats: { hp: 90, attack: 85, defense: 100, speed: 85 },
    rarity: 'legendary',
  },
  {
    id: 145,
    name: 'Zapdos',
    types: ['Electric', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png',
    baseStats: { hp: 90, attack: 90, defense: 85, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 146,
    name: 'Moltres',
    types: ['Fire', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png',
    baseStats: { hp: 90, attack: 100, defense: 90, speed: 90 },
    rarity: 'legendary',
  },
  {
    id: 149,
    name: 'Dragonite',
    types: ['Dragon', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png',
    baseStats: { hp: 91, attack: 134, defense: 95, speed: 80 },
    rarity: 'legendary',
  },
  {
    id: 150,
    name: 'Mewtwo',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
    baseStats: { hp: 106, attack: 110, defense: 90, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 151,
    name: 'Mew',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png',
    baseStats: { hp: 100, attack: 100, defense: 100, speed: 100 },
    rarity: 'legendary',
  },
]

export function getRandomPokemonByRarity(rarity: Rarity): Pokemon {
  const pokemonByRarity = POKEMON_DATA.filter((p) => p.rarity === rarity)
  const randomIndex = Math.floor(Math.random() * pokemonByRarity.length)
  return pokemonByRarity[randomIndex]
}

export function getPokemonById(id: number): Pokemon | undefined {
  return POKEMON_DATA.find((p) => p.id === id)
}
