import type { Pokemon, Rarity } from '../types/pokemon'

export const POKEMON_DATA: Pokemon[] = [
  // Common Pokemon
  {
    id: 1,
    name: 'Bulbasaur',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
    baseStats: { hp: 45, attack: 49, defense: 49, speed: 45 },
    rarity: 'common',
    evolvesTo: 2,
    evolutionLevel: 16,
  },
  {
    id: 4,
    name: 'Charmander',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    baseStats: { hp: 39, attack: 52, defense: 43, speed: 65 },
    rarity: 'common',
    evolvesTo: 5,
    evolutionLevel: 16,
  },
  {
    id: 7,
    name: 'Squirtle',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    baseStats: { hp: 44, attack: 48, defense: 65, speed: 43 },
    rarity: 'common',
    evolvesTo: 8,
    evolutionLevel: 16,
  },
  {
    id: 10,
    name: 'Caterpie',
    types: ['Bug'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
    baseStats: { hp: 45, attack: 30, defense: 35, speed: 45 },
    rarity: 'common',
  },
  {
    id: 13,
    name: 'Weedle',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
    baseStats: { hp: 40, attack: 35, defense: 30, speed: 50 },
    rarity: 'common',
  },
  {
    id: 16,
    name: 'Pidgey',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
    baseStats: { hp: 40, attack: 45, defense: 40, speed: 56 },
    rarity: 'common',
  },
  {
    id: 19,
    name: 'Rattata',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
    baseStats: { hp: 30, attack: 56, defense: 35, speed: 72 },
    rarity: 'common',
  },
  {
    id: 25,
    name: 'Pikachu',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    baseStats: { hp: 35, attack: 55, defense: 40, speed: 90 },
    rarity: 'uncommon',
  },
  // Uncommon Pokemon
  {
    id: 35,
    name: 'Clefairy',
    types: ['Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
    baseStats: { hp: 70, attack: 45, defense: 48, speed: 35 },
    rarity: 'uncommon',
  },
  {
    id: 37,
    name: 'Vulpix',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
    baseStats: { hp: 38, attack: 41, defense: 40, speed: 65 },
    rarity: 'uncommon',
  },
  {
    id: 39,
    name: 'Jigglypuff',
    types: ['Normal', 'Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
    baseStats: { hp: 115, attack: 45, defense: 20, speed: 20 },
    rarity: 'uncommon',
  },
  {
    id: 41,
    name: 'Zubat',
    types: ['Poison', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 55 },
    rarity: 'uncommon',
  },
  {
    id: 43,
    name: 'Oddish',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
    baseStats: { hp: 45, attack: 50, defense: 55, speed: 30 },
    rarity: 'uncommon',
  },
  {
    id: 50,
    name: 'Diglett',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',
    baseStats: { hp: 10, attack: 55, defense: 25, speed: 95 },
    rarity: 'uncommon',
  },
  {
    id: 52,
    name: 'Meowth',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 90 },
    rarity: 'uncommon',
  },
  {
    id: 54,
    name: 'Psyduck',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
    baseStats: { hp: 50, attack: 52, defense: 48, speed: 55 },
    rarity: 'uncommon',
  },
  // Rare Pokemon
  {
    id: 58,
    name: 'Growlithe',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
    baseStats: { hp: 55, attack: 70, defense: 45, speed: 60 },
    rarity: 'rare',
  },
  {
    id: 60,
    name: 'Poliwag',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
    baseStats: { hp: 40, attack: 50, defense: 40, speed: 90 },
    rarity: 'rare',
  },
  {
    id: 63,
    name: 'Abra',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
    baseStats: { hp: 25, attack: 20, defense: 15, speed: 90 },
    rarity: 'rare',
  },
  {
    id: 66,
    name: 'Machop',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
    baseStats: { hp: 70, attack: 80, defense: 50, speed: 35 },
    rarity: 'rare',
  },
  {
    id: 69,
    name: 'Bellsprout',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
    baseStats: { hp: 50, attack: 75, defense: 35, speed: 40 },
    rarity: 'rare',
  },
  {
    id: 72,
    name: 'Tentacool',
    types: ['Water', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
    baseStats: { hp: 40, attack: 40, defense: 35, speed: 70 },
    rarity: 'rare',
  },
  {
    id: 74,
    name: 'Geodude',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
    baseStats: { hp: 40, attack: 80, defense: 100, speed: 20 },
    rarity: 'rare',
  },
  {
    id: 77,
    name: 'Ponyta',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
    baseStats: { hp: 50, attack: 85, defense: 55, speed: 90 },
    rarity: 'rare',
  },
  {
    id: 79,
    name: 'Slowpoke',
    types: ['Water', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
    baseStats: { hp: 90, attack: 65, defense: 65, speed: 15 },
    rarity: 'rare',
  },
  {
    id: 81,
    name: 'Magnemite',
    types: ['Electric', 'Steel'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
    baseStats: { hp: 25, attack: 35, defense: 70, speed: 45 },
    rarity: 'rare',
  },
  // Epic Pokemon
  {
    id: 83,
    name: 'Farfetchd',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
    baseStats: { hp: 52, attack: 90, defense: 55, speed: 60 },
    rarity: 'epic',
  },
  {
    id: 86,
    name: 'Seel',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
    baseStats: { hp: 65, attack: 45, defense: 55, speed: 45 },
    rarity: 'epic',
  },
  {
    id: 88,
    name: 'Grimer',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
    baseStats: { hp: 80, attack: 80, defense: 50, speed: 25 },
    rarity: 'epic',
  },
  {
    id: 90,
    name: 'Shellder',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
    baseStats: { hp: 30, attack: 65, defense: 100, speed: 40 },
    rarity: 'epic',
  },
  {
    id: 92,
    name: 'Gastly',
    types: ['Ghost', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
    baseStats: { hp: 30, attack: 35, defense: 30, speed: 80 },
    rarity: 'epic',
  },
  {
    id: 95,
    name: 'Onix',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
    baseStats: { hp: 35, attack: 45, defense: 160, speed: 70 },
    rarity: 'epic',
  },
  {
    id: 96,
    name: 'Drowzee',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
    baseStats: { hp: 60, attack: 48, defense: 45, speed: 42 },
    rarity: 'epic',
  },
  {
    id: 98,
    name: 'Krabby',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
    baseStats: { hp: 30, attack: 105, defense: 90, speed: 50 },
    rarity: 'epic',
  },
  {
    id: 100,
    name: 'Voltorb',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
    baseStats: { hp: 40, attack: 30, defense: 50, speed: 100 },
    rarity: 'epic',
  },
  {
    id: 104,
    name: 'Cubone',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png',
    baseStats: { hp: 50, attack: 50, defense: 95, speed: 35 },
    rarity: 'epic',
  },
  // Legendary Pokemon
  {
    id: 123,
    name: 'Scyther',
    types: ['Bug', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
    baseStats: { hp: 70, attack: 110, defense: 80, speed: 105 },
    rarity: 'legendary',
  },
  {
    id: 124,
    name: 'Jynx',
    types: ['Ice', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
    baseStats: { hp: 65, attack: 50, defense: 35, speed: 95 },
    rarity: 'legendary',
  },
  {
    id: 126,
    name: 'Magmar',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
    baseStats: { hp: 65, attack: 95, defense: 57, speed: 93 },
    rarity: 'legendary',
  },
  {
    id: 129,
    name: 'Magikarp',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
    baseStats: { hp: 20, attack: 10, defense: 55, speed: 80 },
    rarity: 'common',
  },
  {
    id: 130,
    name: 'Gyarados',
    types: ['Water', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png',
    baseStats: { hp: 95, attack: 125, defense: 79, speed: 81 },
    rarity: 'legendary',
  },
  {
    id: 131,
    name: 'Lapras',
    types: ['Water', 'Ice'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png',
    baseStats: { hp: 130, attack: 85, defense: 80, speed: 60 },
    rarity: 'legendary',
  },
  {
    id: 133,
    name: 'Eevee',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    baseStats: { hp: 55, attack: 55, defense: 50, speed: 55 },
    rarity: 'rare',
    evolvesTo: 135,
    evolutionLevel: 20,
  },
  {
    id: 135,
    name: 'Jolteon',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
    baseStats: { hp: 65, attack: 65, defense: 60, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 137,
    name: 'Vaporeon',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png',
    baseStats: { hp: 130, attack: 65, defense: 60, speed: 65 },
    rarity: 'legendary',
  },
  {
    id: 143,
    name: 'Snorlax',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
    baseStats: { hp: 160, attack: 110, defense: 65, speed: 30 },
    rarity: 'legendary',
  },
  {
    id: 144,
    name: 'Articuno',
    types: ['Ice', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png',
    baseStats: { hp: 90, attack: 85, defense: 100, speed: 85 },
    rarity: 'legendary',
  },
  {
    id: 145,
    name: 'Zapdos',
    types: ['Electric', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png',
    baseStats: { hp: 90, attack: 90, defense: 85, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 146,
    name: 'Moltres',
    types: ['Fire', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png',
    baseStats: { hp: 90, attack: 100, defense: 90, speed: 90 },
    rarity: 'legendary',
  },
  {
    id: 149,
    name: 'Dragonite',
    types: ['Dragon', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png',
    baseStats: { hp: 91, attack: 134, defense: 95, speed: 80 },
    rarity: 'legendary',
  },
  {
    id: 150,
    name: 'Mewtwo',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
    baseStats: { hp: 106, attack: 110, defense: 90, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 151,
    name: 'Mew',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png',
    baseStats: { hp: 100, attack: 100, defense: 100, speed: 100 },
    rarity: 'legendary',
  },
]

export function getRandomPokemonByRarity(rarity: Rarity): Pokemon {
  const pokemonByRarity = POKEMON_DATA.filter((p) => p.rarity === rarity)
  const randomIndex = Math.floor(Math.random() * pokemonByRarity.length)
  return pokemonByRarity[randomIndex]
}

export function getPokemonById(id: number): Pokemon | undefined {
  return POKEMON_DATA.find((p) => p.id === id)
}
