import type { Pokemon, Rarity } from '../types/pokemon'

export const POKEMON_DATA: Pokemon[] = [
  // Common Pokemon
  {
    id: 1,
    name: 'Bulbasaur',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
    baseStats: { hp: 45, attack: 49, defense: 49, speed: 45 },
    rarity: 'common',
    evolvesTo: 2,
    evolutionLevel: 16,
  },
  {
    id: 2,
    name: 'Ivysaur',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
    baseStats: { hp: 60, attack: 62, defense: 63, speed: 60 },
    rarity: 'uncommon',
    evolvesTo: 3,
    evolutionLevel: 32,
  },
  {
    id: 3,
    name: 'Venusaur',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
    baseStats: { hp: 80, attack: 82, defense: 83, speed: 80 },
    rarity: 'epic',
  },
  {
    id: 4,
    name: 'Charmander',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    baseStats: { hp: 39, attack: 52, defense: 43, speed: 65 },
    rarity: 'common',
    evolvesTo: 5,
    evolutionLevel: 16,
  },
  {
    id: 5,
    name: 'Charmeleon',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
    baseStats: { hp: 58, attack: 64, defense: 58, speed: 80 },
    rarity: 'uncommon',
    evolvesTo: 6,
    evolutionLevel: 36,
  },
  {
    id: 6,
    name: 'Charizard',
    types: ['Fire', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
    baseStats: { hp: 78, attack: 84, defense: 78, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 7,
    name: 'Squirtle',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    baseStats: { hp: 44, attack: 48, defense: 65, speed: 43 },
    rarity: 'common',
    evolvesTo: 8,
    evolutionLevel: 16,
  },
  {
    id: 8,
    name: 'Wartortle',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
    baseStats: { hp: 59, attack: 63, defense: 80, speed: 58 },
    rarity: 'uncommon',
    evolvesTo: 9,
    evolutionLevel: 36,
  },
  {
    id: 9,
    name: 'Blastoise',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
    baseStats: { hp: 79, attack: 83, defense: 100, speed: 78 },
    rarity: 'legendary',
  },
  {
    id: 10,
    name: 'Caterpie',
    types: ['Bug'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
    baseStats: { hp: 45, attack: 30, defense: 35, speed: 45 },
    rarity: 'common',
    evolvesTo: 11,
    evolutionLevel: 7,
  },
  {
    id: 11,
    name: 'Metapod',
    types: ['Bug'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
    baseStats: { hp: 50, attack: 20, defense: 55, speed: 30 },
    rarity: 'common',
    evolvesTo: 12,
    evolutionLevel: 10,
  },
  {
    id: 12,
    name: 'Butterfree',
    types: ['Bug', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
    baseStats: { hp: 60, attack: 45, defense: 50, speed: 70 },
    rarity: 'uncommon',
  },
  {
    id: 13,
    name: 'Weedle',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
    baseStats: { hp: 40, attack: 35, defense: 30, speed: 50 },
    rarity: 'common',
    evolvesTo: 14,
    evolutionLevel: 7,
  },
  {
    id: 14,
    name: 'Kakuna',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
    baseStats: { hp: 45, attack: 25, defense: 50, speed: 35 },
    rarity: 'common',
    evolvesTo: 15,
    evolutionLevel: 10,
  },
  {
    id: 15,
    name: 'Beedrill',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
    baseStats: { hp: 65, attack: 90, defense: 40, speed: 75 },
    rarity: 'uncommon',
  },
  {
    id: 16,
    name: 'Pidgey',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
    baseStats: { hp: 40, attack: 45, defense: 40, speed: 56 },
    rarity: 'common',
    evolvesTo: 17,
    evolutionLevel: 18,
  },
  {
    id: 17,
    name: 'Pidgeotto',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
    baseStats: { hp: 63, attack: 60, defense: 55, speed: 71 },
    rarity: 'uncommon',
    evolvesTo: 18,
    evolutionLevel: 36,
  },
  {
    id: 18,
    name: 'Pidgeot',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
    baseStats: { hp: 83, attack: 80, defense: 75, speed: 101 },
    rarity: 'rare',
  },
  {
    id: 19,
    name: 'Rattata',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
    baseStats: { hp: 30, attack: 56, defense: 35, speed: 72 },
    rarity: 'common',
    evolvesTo: 20,
    evolutionLevel: 20,
  },
  {
    id: 20,
    name: 'Raticate',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
    baseStats: { hp: 55, attack: 81, defense: 60, speed: 97 },
    rarity: 'uncommon',
  },
  {
    id: 21,
    name: 'Spearow',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
    baseStats: { hp: 40, attack: 60, defense: 30, speed: 70 },
    rarity: 'common',
    evolvesTo: 22,
    evolutionLevel: 20,
  },
  {
    id: 22,
    name: 'Fearow',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',
    baseStats: { hp: 65, attack: 90, defense: 65, speed: 100 },
    rarity: 'uncommon',
  },
  {
    id: 23,
    name: 'Ekans',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
    baseStats: { hp: 35, attack: 60, defense: 44, speed: 55 },
    rarity: 'common',
    evolvesTo: 24,
    evolutionLevel: 22,
  },
  {
    id: 24,
    name: 'Arbok',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png',
    baseStats: { hp: 60, attack: 95, defense: 69, speed: 80 },
    rarity: 'uncommon',
  },
  {
    id: 27,
    name: 'Sandshrew',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',
    baseStats: { hp: 50, attack: 75, defense: 85, speed: 40 },
    rarity: 'uncommon',
    evolvesTo: 28,
    evolutionLevel: 22,
  },
  {
    id: 28,
    name: 'Sandslash',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png',
    baseStats: { hp: 75, attack: 100, defense: 110, speed: 65 },
    rarity: 'rare',
  },
  {
    id: 29,
    name: 'Nidoran♀',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png',
    baseStats: { hp: 55, attack: 47, defense: 52, speed: 41 },
    rarity: 'uncommon',
    evolvesTo: 30,
    evolutionLevel: 16,
  },
  {
    id: 30,
    name: 'Nidorina',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png',
    baseStats: { hp: 70, attack: 62, defense: 67, speed: 56 },
    rarity: 'uncommon',
    evolvesTo: 31,
    evolutionLevel: 30,
  },
  {
    id: 31,
    name: 'Nidoqueen',
    types: ['Poison', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png',
    baseStats: { hp: 90, attack: 92, defense: 87, speed: 76 },
    rarity: 'legendary',
  },
  {
    id: 32,
    name: 'Nidoran♂',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',
    baseStats: { hp: 46, attack: 57, defense: 40, speed: 50 },
    rarity: 'uncommon',
    evolvesTo: 33,
    evolutionLevel: 16,
  },
  {
    id: 33,
    name: 'Nidorino',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png',
    baseStats: { hp: 61, attack: 72, defense: 57, speed: 65 },
    rarity: 'uncommon',
    evolvesTo: 34,
    evolutionLevel: 30,
  },
  {
    id: 34,
    name: 'Nidoking',
    types: ['Poison', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png',
    baseStats: { hp: 81, attack: 102, defense: 77, speed: 85 },
    rarity: 'legendary',
  },
  {
    id: 25,
    name: 'Pikachu',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    baseStats: { hp: 35, attack: 55, defense: 40, speed: 90 },
    rarity: 'uncommon',
    evolvesTo: 26,
    evolutionLevel: 25,
  },
  {
    id: 26,
    name: 'Raichu',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',
    baseStats: { hp: 60, attack: 90, defense: 55, speed: 110 },
    rarity: 'rare',
  },
  // Uncommon Pokemon
  {
    id: 35,
    name: 'Clefairy',
    types: ['Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
    baseStats: { hp: 70, attack: 45, defense: 48, speed: 35 },
    rarity: 'uncommon',
    evolvesTo: 36,
    evolutionLevel: 25,
  },
  {
    id: 36,
    name: 'Clefable',
    types: ['Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',
    baseStats: { hp: 95, attack: 70, defense: 73, speed: 60 },
    rarity: 'rare',
  },
  {
    id: 37,
    name: 'Vulpix',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
    baseStats: { hp: 38, attack: 41, defense: 40, speed: 65 },
    rarity: 'uncommon',
    evolvesTo: 38,
    evolutionLevel: 25,
  },
  {
    id: 38,
    name: 'Ninetales',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',
    baseStats: { hp: 73, attack: 76, defense: 75, speed: 100 },
    rarity: 'rare',
  },
  {
    id: 39,
    name: 'Jigglypuff',
    types: ['Normal', 'Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
    baseStats: { hp: 115, attack: 45, defense: 20, speed: 20 },
    rarity: 'uncommon',
    evolvesTo: 40,
    evolutionLevel: 25,
  },
  {
    id: 40,
    name: 'Wigglytuff',
    types: ['Normal', 'Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',
    baseStats: { hp: 140, attack: 70, defense: 45, speed: 45 },
    rarity: 'rare',
  },
  {
    id: 41,
    name: 'Zubat',
    types: ['Poison', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 55 },
    rarity: 'uncommon',
    evolvesTo: 42,
    evolutionLevel: 22,
  },
  {
    id: 42,
    name: 'Golbat',
    types: ['Poison', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',
    baseStats: { hp: 75, attack: 80, defense: 70, speed: 90 },
    rarity: 'rare',
    evolvesTo: 169,
    evolutionLevel: 40,
  },
  {
    id: 169,
    name: 'Crobat',
    types: ['Poison', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/169.png',
    baseStats: { hp: 85, attack: 90, defense: 80, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 43,
    name: 'Oddish',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
    baseStats: { hp: 45, attack: 50, defense: 55, speed: 30 },
    rarity: 'uncommon',
    evolvesTo: 44,
    evolutionLevel: 21,
  },
  {
    id: 44,
    name: 'Gloom',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',
    baseStats: { hp: 60, attack: 65, defense: 70, speed: 40 },
    rarity: 'uncommon',
    evolvesTo: 45,
    evolutionLevel: 30,
  },
  {
    id: 45,
    name: 'Vileplume',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',
    baseStats: { hp: 75, attack: 80, defense: 85, speed: 50 },
    rarity: 'rare',
  },
  {
    id: 182,
    name: 'Bellossom',
    types: ['Grass'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/182.png',
    baseStats: { hp: 75, attack: 80, defense: 95, speed: 50 },
    rarity: 'legendary',
  },
  {
    id: 46,
    name: 'Paras',
    types: ['Bug', 'Grass'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',
    baseStats: { hp: 35, attack: 70, defense: 55, speed: 25 },
    rarity: 'uncommon',
    evolvesTo: 47,
    evolutionLevel: 24,
  },
  {
    id: 47,
    name: 'Parasect',
    types: ['Bug', 'Grass'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png',
    baseStats: { hp: 60, attack: 95, defense: 80, speed: 30 },
    rarity: 'rare',
  },
  {
    id: 48,
    name: 'Venonat',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
    baseStats: { hp: 60, attack: 55, defense: 50, speed: 45 },
    rarity: 'uncommon',
    evolvesTo: 49,
    evolutionLevel: 31,
  },
  {
    id: 49,
    name: 'Venomoth',
    types: ['Bug', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png',
    baseStats: { hp: 70, attack: 65, defense: 60, speed: 90 },
    rarity: 'rare',
  },
  {
    id: 50,
    name: 'Diglett',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',
    baseStats: { hp: 10, attack: 55, defense: 25, speed: 95 },
    rarity: 'uncommon',
    evolvesTo: 51,
    evolutionLevel: 26,
  },
  {
    id: 51,
    name: 'Dugtrio',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png',
    baseStats: { hp: 35, attack: 80, defense: 50, speed: 120 },
    rarity: 'rare',
  },
  {
    id: 52,
    name: 'Meowth',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
    baseStats: { hp: 40, attack: 45, defense: 35, speed: 90 },
    rarity: 'uncommon',
    evolvesTo: 53,
    evolutionLevel: 28,
  },
  {
    id: 53,
    name: 'Persian',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png',
    baseStats: { hp: 65, attack: 70, defense: 60, speed: 115 },
    rarity: 'rare',
  },
  {
    id: 56,
    name: 'Mankey',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png',
    baseStats: { hp: 40, attack: 80, defense: 35, speed: 70 },
    rarity: 'uncommon',
    evolvesTo: 57,
    evolutionLevel: 28,
  },
  {
    id: 57,
    name: 'Primeape',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png',
    baseStats: { hp: 65, attack: 105, defense: 60, speed: 95 },
    rarity: 'rare',
  },
  {
    id: 54,
    name: 'Psyduck',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
    baseStats: { hp: 50, attack: 52, defense: 48, speed: 55 },
    rarity: 'uncommon',
    evolvesTo: 55,
    evolutionLevel: 33,
  },
  {
    id: 55,
    name: 'Golduck',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png',
    baseStats: { hp: 80, attack: 82, defense: 78, speed: 80 },
    rarity: 'rare',
  },
  // Rare Pokemon
  {
    id: 58,
    name: 'Growlithe',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
    baseStats: { hp: 55, attack: 70, defense: 45, speed: 60 },
    rarity: 'rare',
    evolvesTo: 59,
    evolutionLevel: 25,
  },
  {
    id: 59,
    name: 'Arcanine',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png',
    baseStats: { hp: 90, attack: 110, defense: 80, speed: 95 },
    rarity: 'legendary',
  },
  {
    id: 60,
    name: 'Poliwag',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
    baseStats: { hp: 40, attack: 50, defense: 40, speed: 90 },
    rarity: 'rare',
    evolvesTo: 61,
    evolutionLevel: 25,
  },
  {
    id: 61,
    name: 'Poliwhirl',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png',
    baseStats: { hp: 65, attack: 65, defense: 65, speed: 90 },
    rarity: 'rare',
    evolvesTo: 62,
    evolutionLevel: 35,
  },
  {
    id: 62,
    name: 'Poliwrath',
    types: ['Water', 'Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png',
    baseStats: { hp: 90, attack: 95, defense: 95, speed: 70 },
    rarity: 'legendary',
  },
  {
    id: 63,
    name: 'Abra',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
    baseStats: { hp: 25, attack: 20, defense: 15, speed: 90 },
    rarity: 'rare',
    evolvesTo: 64,
    evolutionLevel: 16,
  },
  {
    id: 64,
    name: 'Kadabra',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png',
    baseStats: { hp: 40, attack: 35, defense: 30, speed: 105 },
    rarity: 'rare',
    evolvesTo: 65,
    evolutionLevel: 30,
  },
  {
    id: 65,
    name: 'Alakazam',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png',
    baseStats: { hp: 55, attack: 50, defense: 45, speed: 120 },
    rarity: 'legendary',
  },
  {
    id: 66,
    name: 'Machop',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
    baseStats: { hp: 70, attack: 80, defense: 50, speed: 35 },
    rarity: 'rare',
    evolvesTo: 67,
    evolutionLevel: 28,
  },
  {
    id: 67,
    name: 'Machoke',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png',
    baseStats: { hp: 80, attack: 100, defense: 70, speed: 45 },
    rarity: 'rare',
    evolvesTo: 68,
    evolutionLevel: 40,
  },
  {
    id: 68,
    name: 'Machamp',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png',
    baseStats: { hp: 90, attack: 130, defense: 80, speed: 55 },
    rarity: 'legendary',
  },
  {
    id: 69,
    name: 'Bellsprout',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
    baseStats: { hp: 50, attack: 75, defense: 35, speed: 40 },
    rarity: 'rare',
    evolvesTo: 70,
    evolutionLevel: 21,
  },
  {
    id: 70,
    name: 'Weepinbell',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png',
    baseStats: { hp: 65, attack: 90, defense: 50, speed: 55 },
    rarity: 'rare',
    evolvesTo: 71,
    evolutionLevel: 30,
  },
  {
    id: 71,
    name: 'Victreebel',
    types: ['Grass', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png',
    baseStats: { hp: 80, attack: 105, defense: 65, speed: 70 },
    rarity: 'legendary',
  },
  {
    id: 72,
    name: 'Tentacool',
    types: ['Water', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
    baseStats: { hp: 40, attack: 40, defense: 35, speed: 70 },
    rarity: 'rare',
    evolvesTo: 73,
    evolutionLevel: 30,
  },
  {
    id: 73,
    name: 'Tentacruel',
    types: ['Water', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png',
    baseStats: { hp: 80, attack: 70, defense: 65, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 74,
    name: 'Geodude',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
    baseStats: { hp: 40, attack: 80, defense: 100, speed: 20 },
    rarity: 'rare',
    evolvesTo: 75,
    evolutionLevel: 25,
  },
  {
    id: 75,
    name: 'Graveler',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png',
    baseStats: { hp: 55, attack: 95, defense: 115, speed: 35 },
    rarity: 'rare',
    evolvesTo: 76,
    evolutionLevel: 40,
  },
  {
    id: 76,
    name: 'Golem',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png',
    baseStats: { hp: 80, attack: 120, defense: 130, speed: 45 },
    rarity: 'legendary',
  },
  {
    id: 77,
    name: 'Ponyta',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
    baseStats: { hp: 50, attack: 85, defense: 55, speed: 90 },
    rarity: 'rare',
    evolvesTo: 78,
    evolutionLevel: 40,
  },
  {
    id: 78,
    name: 'Rapidash',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png',
    baseStats: { hp: 65, attack: 100, defense: 70, speed: 105 },
    rarity: 'legendary',
  },
  {
    id: 79,
    name: 'Slowpoke',
    types: ['Water', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
    baseStats: { hp: 90, attack: 65, defense: 65, speed: 15 },
    rarity: 'rare',
    evolvesTo: 80,
    evolutionLevel: 37,
  },
  {
    id: 80,
    name: 'Slowbro',
    types: ['Water', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png',
    baseStats: { hp: 95, attack: 75, defense: 110, speed: 30 },
    rarity: 'legendary',
    evolvesTo: 199,
    evolutionLevel: 45,
  },
  {
    id: 199,
    name: 'Slowking',
    types: ['Water', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/199.png',
    baseStats: { hp: 95, attack: 75, defense: 80, speed: 30 },
    rarity: 'legendary',
  },
  {
    id: 81,
    name: 'Magnemite',
    types: ['Electric', 'Steel'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
    baseStats: { hp: 25, attack: 35, defense: 70, speed: 45 },
    rarity: 'rare',
    evolvesTo: 82,
    evolutionLevel: 30,
  },
  {
    id: 82,
    name: 'Magneton',
    types: ['Electric', 'Steel'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
    baseStats: { hp: 50, attack: 60, defense: 95, speed: 70 },
    rarity: 'legendary',
    evolvesTo: 462,
    evolutionLevel: 50,
  },
  {
    id: 462,
    name: 'Magnezone',
    types: ['Electric', 'Steel'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/462.png',
    baseStats: { hp: 70, attack: 70, defense: 115, speed: 60 },
    rarity: 'legendary',
  },
  // Epic Pokemon
  {
    id: 83,
    name: 'Farfetchd',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
    baseStats: { hp: 52, attack: 90, defense: 55, speed: 60 },
    rarity: 'epic',
    evolvesTo: 865,
    evolutionLevel: 35,
  },
  {
    id: 865,
    name: 'Sirfetchd',
    types: ['Fighting', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/865.png',
    baseStats: { hp: 62, attack: 135, defense: 95, speed: 65 },
    rarity: 'legendary',
  },
  {
    id: 84,
    name: 'Doduo',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png',
    baseStats: { hp: 35, attack: 85, defense: 45, speed: 75 },
    rarity: 'epic',
    evolvesTo: 85,
    evolutionLevel: 31,
  },
  {
    id: 85,
    name: 'Dodrio',
    types: ['Normal', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png',
    baseStats: { hp: 60, attack: 110, defense: 70, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 86,
    name: 'Seel',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
    baseStats: { hp: 65, attack: 45, defense: 55, speed: 45 },
    rarity: 'epic',
    evolvesTo: 87,
    evolutionLevel: 34,
  },
  {
    id: 87,
    name: 'Dewgong',
    types: ['Water', 'Ice'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
    baseStats: { hp: 90, attack: 70, defense: 80, speed: 70 },
    rarity: 'legendary',
  },
  {
    id: 88,
    name: 'Grimer',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
    baseStats: { hp: 80, attack: 80, defense: 50, speed: 25 },
    rarity: 'epic',
    evolvesTo: 89,
    evolutionLevel: 38,
  },
  {
    id: 89,
    name: 'Muk',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png',
    baseStats: { hp: 105, attack: 105, defense: 75, speed: 50 },
    rarity: 'legendary',
  },
  {
    id: 90,
    name: 'Shellder',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
    baseStats: { hp: 30, attack: 65, defense: 100, speed: 40 },
    rarity: 'epic',
    evolvesTo: 91,
    evolutionLevel: 30,
  },
  {
    id: 91,
    name: 'Cloyster',
    types: ['Water', 'Ice'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
    baseStats: { hp: 50, attack: 95, defense: 180, speed: 70 },
    rarity: 'legendary',
  },
  {
    id: 92,
    name: 'Gastly',
    types: ['Ghost', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
    baseStats: { hp: 30, attack: 35, defense: 30, speed: 80 },
    rarity: 'epic',
    evolvesTo: 93,
    evolutionLevel: 25,
  },
  {
    id: 93,
    name: 'Haunter',
    types: ['Ghost', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png',
    baseStats: { hp: 45, attack: 50, defense: 45, speed: 95 },
    rarity: 'epic',
    evolvesTo: 94,
    evolutionLevel: 25,
  },
  {
    id: 94,
    name: 'Gengar',
    types: ['Ghost', 'Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
    baseStats: { hp: 60, attack: 65, defense: 60, speed: 110 },
    rarity: 'legendary',
  },
  {
    id: 95,
    name: 'Onix',
    types: ['Rock', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
    baseStats: { hp: 35, attack: 45, defense: 160, speed: 70 },
    rarity: 'epic',
    evolvesTo: 208,
    evolutionLevel: 40,
  },
  {
    id: 102,
    name: 'Exeggcute',
    types: ['Grass', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png',
    baseStats: { hp: 60, attack: 40, defense: 60, speed: 40 },
    rarity: 'epic',
    evolvesTo: 103,
    evolutionLevel: 28,
  },
  {
    id: 103,
    name: 'Exeggutor',
    types: ['Grass', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png',
    baseStats: { hp: 95, attack: 95, defense: 85, speed: 55 },
    rarity: 'legendary',
  },
  {
    id: 96,
    name: 'Drowzee',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
    baseStats: { hp: 60, attack: 48, defense: 45, speed: 42 },
    rarity: 'epic',
    evolvesTo: 97,
    evolutionLevel: 26,
  },
  {
    id: 97,
    name: 'Hypno',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png',
    baseStats: { hp: 85, attack: 73, defense: 70, speed: 67 },
    rarity: 'legendary',
  },
  {
    id: 98,
    name: 'Krabby',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
    baseStats: { hp: 30, attack: 105, defense: 90, speed: 50 },
    rarity: 'epic',
    evolvesTo: 99,
    evolutionLevel: 28,
  },
  {
    id: 99,
    name: 'Kingler',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png',
    baseStats: { hp: 55, attack: 130, defense: 115, speed: 75 },
    rarity: 'legendary',
  },
  {
    id: 100,
    name: 'Voltorb',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
    baseStats: { hp: 40, attack: 30, defense: 50, speed: 100 },
    rarity: 'epic',
    evolvesTo: 101,
    evolutionLevel: 30,
  },
  {
    id: 101,
    name: 'Electrode',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png',
    baseStats: { hp: 60, attack: 50, defense: 70, speed: 140 },
    rarity: 'legendary',
  },
  {
    id: 104,
    name: 'Cubone',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png',
    baseStats: { hp: 50, attack: 50, defense: 95, speed: 35 },
    rarity: 'epic',
    evolvesTo: 105,
    evolutionLevel: 28,
  },
  {
    id: 105,
    name: 'Marowak',
    types: ['Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png',
    baseStats: { hp: 60, attack: 80, defense: 110, speed: 45 },
    rarity: 'legendary',
  },
  {
    id: 106,
    name: 'Hitmonlee',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png',
    baseStats: { hp: 50, attack: 120, defense: 53, speed: 87 },
    rarity: 'legendary',
  },
  {
    id: 107,
    name: 'Hitmonchan',
    types: ['Fighting'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png',
    baseStats: { hp: 50, attack: 105, defense: 79, speed: 76 },
    rarity: 'legendary',
  },
  {
    id: 108,
    name: 'Lickitung',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png',
    baseStats: { hp: 90, attack: 55, defense: 75, speed: 30 },
    rarity: 'epic',
    evolvesTo: 463,
    evolutionLevel: 50,
  },
  {
    id: 463,
    name: 'Lickilicky',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/463.png',
    baseStats: { hp: 110, attack: 85, defense: 95, speed: 50 },
    rarity: 'legendary',
  },
  {
    id: 109,
    name: 'Koffing',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png',
    baseStats: { hp: 40, attack: 65, defense: 95, speed: 35 },
    rarity: 'epic',
    evolvesTo: 110,
    evolutionLevel: 35,
  },
  {
    id: 110,
    name: 'Weezing',
    types: ['Poison'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png',
    baseStats: { hp: 65, attack: 90, defense: 120, speed: 60 },
    rarity: 'legendary',
  },
  {
    id: 111,
    name: 'Rhyhorn',
    types: ['Ground', 'Rock'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png',
    baseStats: { hp: 80, attack: 85, defense: 95, speed: 25 },
    rarity: 'epic',
    evolvesTo: 112,
    evolutionLevel: 42,
  },
  {
    id: 112,
    name: 'Rhydon',
    types: ['Ground', 'Rock'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png',
    baseStats: { hp: 105, attack: 130, defense: 120, speed: 40 },
    rarity: 'legendary',
    evolvesTo: 464,
    evolutionLevel: 50,
  },
  {
    id: 464,
    name: 'Rhyperior',
    types: ['Ground', 'Rock'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/464.png',
    baseStats: { hp: 115, attack: 140, defense: 130, speed: 40 },
    rarity: 'legendary',
  },
  {
    id: 113,
    name: 'Chansey',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png',
    baseStats: { hp: 250, attack: 5, defense: 5, speed: 50 },
    rarity: 'legendary',
    evolvesTo: 242,
    evolutionLevel: 45,
  },
  {
    id: 242,
    name: 'Blissey',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/242.png',
    baseStats: { hp: 255, attack: 10, defense: 10, speed: 55 },
    rarity: 'legendary',
  },
  {
    id: 114,
    name: 'Tangela',
    types: ['Grass'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png',
    baseStats: { hp: 65, attack: 55, defense: 115, speed: 60 },
    rarity: 'epic',
    evolvesTo: 465,
    evolutionLevel: 50,
  },
  {
    id: 465,
    name: 'Tangrowth',
    types: ['Grass'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/465.png',
    baseStats: { hp: 100, attack: 100, defense: 125, speed: 50 },
    rarity: 'legendary',
  },
  {
    id: 116,
    name: 'Horsea',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png',
    baseStats: { hp: 30, attack: 40, defense: 70, speed: 60 },
    rarity: 'epic',
    evolvesTo: 117,
    evolutionLevel: 32,
  },
  {
    id: 117,
    name: 'Seadra',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png',
    baseStats: { hp: 55, attack: 65, defense: 95, speed: 85 },
    rarity: 'legendary',
    evolvesTo: 230,
    evolutionLevel: 45,
  },
  {
    id: 230,
    name: 'Kingdra',
    types: ['Water', 'Dragon'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/230.png',
    baseStats: { hp: 75, attack: 95, defense: 95, speed: 85 },
    rarity: 'legendary',
  },
  {
    id: 118,
    name: 'Goldeen',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png',
    baseStats: { hp: 45, attack: 67, defense: 60, speed: 63 },
    rarity: 'epic',
    evolvesTo: 119,
    evolutionLevel: 33,
  },
  {
    id: 119,
    name: 'Seaking',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png',
    baseStats: { hp: 80, attack: 92, defense: 65, speed: 68 },
    rarity: 'legendary',
  },
  {
    id: 120,
    name: 'Staryu',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png',
    baseStats: { hp: 30, attack: 45, defense: 55, speed: 85 },
    rarity: 'epic',
    evolvesTo: 121,
    evolutionLevel: 30,
  },
  {
    id: 121,
    name: 'Starmie',
    types: ['Water', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png',
    baseStats: { hp: 60, attack: 75, defense: 85, speed: 115 },
    rarity: 'legendary',
  },
  {
    id: 122,
    name: 'Mr. Mime',
    types: ['Psychic', 'Fairy'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png',
    baseStats: { hp: 40, attack: 45, defense: 65, speed: 90 },
    rarity: 'epic',
    evolvesTo: 866,
    evolutionLevel: 42,
  },
  {
    id: 866,
    name: 'Mr. Rime',
    types: ['Ice', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/866.png',
    baseStats: { hp: 75, attack: 65, defense: 70, speed: 95 },
    rarity: 'legendary',
  },
  // Legendary Pokemon
  {
    id: 123,
    name: 'Scyther',
    types: ['Bug', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
    baseStats: { hp: 70, attack: 110, defense: 80, speed: 105 },
    rarity: 'legendary',
    evolvesTo: 212,
    evolutionLevel: 45,
  },
  {
    id: 212,
    name: 'Scizor',
    types: ['Bug', 'Steel'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/212.png',
    baseStats: { hp: 70, attack: 130, defense: 100, speed: 65 },
    rarity: 'legendary',
  },
  {
    id: 124,
    name: 'Jynx',
    types: ['Ice', 'Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
    baseStats: { hp: 65, attack: 50, defense: 35, speed: 95 },
    rarity: 'legendary',
  },
  {
    id: 125,
    name: 'Electabuzz',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png',
    baseStats: { hp: 65, attack: 83, defense: 57, speed: 95 },
    rarity: 'legendary',
    evolvesTo: 466,
    evolutionLevel: 50,
  },
  {
    id: 466,
    name: 'Electivire',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/466.png',
    baseStats: { hp: 75, attack: 123, defense: 67, speed: 95 },
    rarity: 'legendary',
  },
  {
    id: 126,
    name: 'Magmar',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
    baseStats: { hp: 65, attack: 95, defense: 57, speed: 93 },
    rarity: 'legendary',
    evolvesTo: 467,
    evolutionLevel: 50,
  },
  {
    id: 467,
    name: 'Magmortar',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/467.png',
    baseStats: { hp: 75, attack: 95, defense: 67, speed: 83 },
    rarity: 'legendary',
  },
  {
    id: 127,
    name: 'Pinsir',
    types: ['Bug'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png',
    baseStats: { hp: 65, attack: 125, defense: 100, speed: 85 },
    rarity: 'legendary',
  },
  {
    id: 128,
    name: 'Tauros',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png',
    baseStats: { hp: 75, attack: 100, defense: 95, speed: 110 },
    rarity: 'legendary',
  },
  {
    id: 130,
    name: 'Gyarados',
    types: ['Water', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png',
    baseStats: { hp: 95, attack: 125, defense: 79, speed: 81 },
    rarity: 'legendary',
  },
  {
    id: 131,
    name: 'Lapras',
    types: ['Water', 'Ice'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png',
    baseStats: { hp: 130, attack: 85, defense: 80, speed: 60 },
    rarity: 'legendary',
  },
  {
    id: 133,
    name: 'Eevee',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    baseStats: { hp: 55, attack: 55, defense: 50, speed: 55 },
    rarity: 'rare',
    evolvesTo: 135,
    evolutionLevel: 20,
  },
  {
    id: 134,
    name: 'Vaporeon',
    types: ['Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png',
    baseStats: { hp: 130, attack: 65, defense: 60, speed: 65 },
    rarity: 'legendary',
  },
  {
    id: 135,
    name: 'Jolteon',
    types: ['Electric'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
    baseStats: { hp: 65, attack: 65, defense: 60, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 136,
    name: 'Flareon',
    types: ['Fire'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png',
    baseStats: { hp: 65, attack: 130, defense: 60, speed: 65 },
    rarity: 'legendary',
  },
  {
    id: 137,
    name: 'Porygon',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png',
    baseStats: { hp: 65, attack: 60, defense: 70, speed: 40 },
    rarity: 'legendary',
    evolvesTo: 233,
    evolutionLevel: 45,
  },
  {
    id: 233,
    name: 'Porygon2',
    types: ['Normal'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/233.png',
    baseStats: { hp: 85, attack: 80, defense: 90, speed: 60 },
    rarity: 'legendary',
  },
  {
    id: 138,
    name: 'Omanyte',
    types: ['Rock', 'Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png',
    baseStats: { hp: 35, attack: 40, defense: 100, speed: 35 },
    rarity: 'epic',
    evolvesTo: 139,
    evolutionLevel: 40,
  },
  {
    id: 139,
    name: 'Omastar',
    types: ['Rock', 'Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png',
    baseStats: { hp: 70, attack: 60, defense: 125, speed: 55 },
    rarity: 'legendary',
  },
  {
    id: 140,
    name: 'Kabuto',
    types: ['Rock', 'Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png',
    baseStats: { hp: 30, attack: 80, defense: 90, speed: 55 },
    rarity: 'epic',
    evolvesTo: 141,
    evolutionLevel: 40,
  },
  {
    id: 141,
    name: 'Kabutops',
    types: ['Rock', 'Water'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png',
    baseStats: { hp: 60, attack: 115, defense: 105, speed: 80 },
    rarity: 'legendary',
  },
  {
    id: 142,
    name: 'Aerodactyl',
    types: ['Rock', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png',
    baseStats: { hp: 80, attack: 105, defense: 65, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 208,
    name: 'Steelix',
    types: ['Steel', 'Ground'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/208.png',
    baseStats: { hp: 75, attack: 85, defense: 200, speed: 30 },
    rarity: 'legendary',
  },
  {
    id: 144,
    name: 'Articuno',
    types: ['Ice', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png',
    baseStats: { hp: 90, attack: 85, defense: 100, speed: 85 },
    rarity: 'legendary',
  },
  {
    id: 145,
    name: 'Zapdos',
    types: ['Electric', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png',
    baseStats: { hp: 90, attack: 90, defense: 85, speed: 100 },
    rarity: 'legendary',
  },
  {
    id: 146,
    name: 'Moltres',
    types: ['Fire', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png',
    baseStats: { hp: 90, attack: 100, defense: 90, speed: 90 },
    rarity: 'legendary',
  },
  {
    id: 147,
    name: 'Dratini',
    types: ['Dragon'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png',
    baseStats: { hp: 41, attack: 64, defense: 45, speed: 50 },
    rarity: 'epic',
    evolvesTo: 148,
    evolutionLevel: 30,
  },
  {
    id: 148,
    name: 'Dragonair',
    types: ['Dragon'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png',
    baseStats: { hp: 61, attack: 84, defense: 65, speed: 70 },
    rarity: 'epic',
    evolvesTo: 149,
    evolutionLevel: 55,
  },
  {
    id: 149,
    name: 'Dragonite',
    types: ['Dragon', 'Flying'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png',
    baseStats: { hp: 91, attack: 134, defense: 95, speed: 80 },
    rarity: 'legendary',
  },
  {
    id: 150,
    name: 'Mewtwo',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
    baseStats: { hp: 106, attack: 110, defense: 90, speed: 130 },
    rarity: 'legendary',
  },
  {
    id: 151,
    name: 'Mew',
    types: ['Psychic'],
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png',
    baseStats: { hp: 100, attack: 100, defense: 100, speed: 100 },
    rarity: 'legendary',
  },
]

export function getRandomPokemonByRarity(rarity: Rarity): Pokemon {
  const pokemonByRarity = POKEMON_DATA.filter((p) => p.rarity === rarity)
  const randomIndex = Math.floor(Math.random() * pokemonByRarity.length)
  return pokemonByRarity[randomIndex]
}

export function getPokemonById(id: number): Pokemon | undefined {
  return POKEMON_DATA.find((p) => p.id === id)
}
